

USE checkgeom;

CREATE TABLE book_interest (
    ID CHAR(36) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    LIBRARY_TYPE VARCHAR(60) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    EXPLANATION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(60) NOT NULL,
    CREATED_DATE_TIME DATETIME NOT NULL,
    UPDATED_DATE_TIME DATETIME NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE users (
    ID CHAR(36) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    CREATED_DATE_TIME DATETIME NOT NULL,
    UPDATED_DATE_TIME DATETIME NULL,
    AUTH VARCHAR(60) NOT NULL,
    AUTH_CODE INT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;