version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: MYDATABASE
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
# docker exec -it my-mysql mysql -u root -p1234 MYDATABASE
#docker exec -it my-mysql mysql -u root -p
